name: savanna
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - minimap2
  - samtools=1.17
  - bcftools=1.17
  - htslib
  - bedtools
  - pysam
  - jupyter
  - dash
  - pandas
  - numpy
  - scipy=1.4
  - seaborn
  - click
  - black
  - flake8
  - pytest
  - pip
  - pip:
    - pyyaml
