bam_filter:
  min_mapq: 40
  exclude_flags: "0x904"
call:
  bcftools:
    mpileup_setting: "ont"
    max_depth: 10000
    mutation_rate_prior: 0.01
call_filter:
  to_snps: False
  to_biallelic: False
  min_depth: 40
  min_qual: 15